language: node_js
dist: trusty
sudo: required
install:
  - npm install -g bower
  - npm install
  - bower install
script:
  - npm run -s build
  - npm run -s test
notifications:
  email:
    on_success: never
    on_failure: always